<?xml version="1.0" encoding="UTF-8"?> 
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="podcasts">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="podcast" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="titulo" type="xsd:string" />
                            <xsd:element name="podcaster" type="xsd:string"/>
                            <xsd:element name="colaboradores" type="xsd:integer"/>
                            <xsd:element name="genero" type="xsd:string"/>
                            <xsd:element name="duracion" type="xsd:int"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    </xsd:schema>